import fs from 'node:fs'; import path from 'node:path'; import url from 'node:url';
const dir=path.dirname(url.fileURLToPath(import.meta.url)); let fails=0;
const ok=(n,c,d)=>{console.log((c?'  PASS  ':'  FAIL  ')+n+(c?'':'  -> '+JSON.stringify(d)));if(!c)fails++;};
new Function(fs.readFileSync(path.join(dir,'..','quarterly_timeline.js'),'utf8'))();
const Q=globalThis.QTimeline; const FX=JSON.parse(fs.readFileSync(path.join(dir,'..','qt_fixtures.json'),'utf8'));
const cl=(a,b,t)=>Math.abs(a-b)<=(t||1e-9); const arr=(a,b,t)=>a.length===b.length&&a.every((v,i)=>cl(v,b[i],t));
ok('normalized parity', arr(Q.normalized([50,55,60]),FX.normalized));
ok('logReturns parity', arr(Q.logReturns([100,102,101,105]),FX.logReturns));
ok('relativeStrength parity', arr(Q.relativeStrength([100,110,121],[100,105,110.25]).RS,FX.relRS));
const d=Q.drawdowns([100,110,120,100,90,100,115,125]);
ok('drawdown maxDD/avgDD/recovery parity', cl(d.maxDD,FX.maxDD)&&cl(d.avgDD,FX.avgDD)&&d.episodes[0].recoveryDays===FX.recDays);
const r=[0.01,-0.02,0.015,-0.03,0.02,-0.01,0.005];
ok('realized/downside vol parity', cl(Q.realizedVol(r),FX.rvol)&&cl(Q.downsideVol(r),FX.dvol));
const bm=Q.betaMarketModel(FX._inputs.sr,FX._inputs.mr);
ok('beta + HAC t parity', cl(bm.beta,FX.beta)&&cl(bm.t_beta,FX.t_beta));
const es=Q.eventStudy(FX._inputs.sr2,FX._inputs.mr2,50,[-40,-5]);
ok('event study AR + CAR parity', cl(es.AR_event,FX.AR_event)&&cl(es.CAR['-1,1'],FX['CAR_-1_1']));
ok('CAR significance parity', cl(Q.carSignificance([0.02,0.018,0.025,0.015,0.022]).t,FX.carSig_t));
ok('EWMA overlay parity', arr(Q.ewmaOverlay([1,2,3,4,5],20),FX.ewma));
const rd=Q.returnDecomposition(100,120,5,5.5,2.0);
ok('return decomposition parity', cl(rd.fundamentalGrowth,FX.fund)&&cl(rd.distributions,FX.dist));
console.log('\n'+(fails?fails+' PARITY FAILURES':'ALL QT JS<->PY PARITY TESTS PASSED')); process.exit(fails?1:0);
