/* Exact Py<->JS parity for the multi-horizon projection engine: fib_engine.js vs the committed
   tools/fib_golden.json (generated by tools/market_map/fib_ref.py). Half-life, blended daily sigma,
   every per-horizon projection field, and the H1 forecast score must agree to 1e-9 across languages.
   Skip-if-absent (the fixture is seeded by `python3 tools/market_map/fib_ref.py`).
   Run: node tools/test_fib_parity.mjs */
import { createRequire } from 'module';
import fs from 'node:fs';
import path from 'node:path';
import url from 'node:url';
const require = createRequire(import.meta.url);
const here = path.dirname(url.fileURLToPath(import.meta.url));
const F = require('../fib_engine.js');

const fixturePath = path.join(here, 'fib_golden.json');
if (!fs.existsSync(fixturePath)) {
  console.log('SKIP: tools/fib_golden.json absent (seed via `python3 tools/market_map/fib_ref.py`)');
  process.exit(0);
}
let fails = 0;
const ok = (n, c, d) => { console.log((c ? '  PASS  ' : '  FAIL  ') + n + (c ? '' : '  -> ' + JSON.stringify(d))); if (!c) fails++; };
const close = (a, b) => (a == null && b == null) || Math.abs(a - b) <= 1e-9 * (1 + Math.abs(b));

const g = JSON.parse(fs.readFileSync(fixturePath, 'utf8'));
const inp = g.inputs, exp = g.expected;
const hist = inp.closes_hist, priceNow = hist[hist.length - 1], edge = inp.edge;

ok('fib_engine.js exposes API', ['project', 'horizon_sigma', 'decayed_edge', 'blended_sigma_daily', 'fit_halflife', 'score', 'prob_above'].every(k => typeof F[k] === 'function'));
ok('half_life', close(F.fit_halflife(hist), exp.halflife), [F.fit_halflife(hist), exp.halflife]);
const rets = F.logret(hist);
ok('sigmaDaily', close(F.blended_sigma_daily(rets), exp.sigmaDaily), [F.blended_sigma_daily(rets), exp.sigmaDaily]);

const proj = F.project(priceNow, edge, hist, F.horizons('cadence'), { hl: exp.halflife });
exp.projections.forEach((p, i) => {
  const j = proj[i];
  ['projLog', 'projPrice', 'muLog', 'sigmaH', 'zEdge', 'lo', 'hi'].forEach(k => ok('H' + p.H + '.' + k, close(j[k], p[k]), [j[k], p[k]]));
  ok('H' + p.H + '.capped', j.capped === p.capped, [j.capped, p.capped]);
});

const sc = F.score(priceNow, proj[0].projLog, proj[0].sigmaH, inp.realized_next);
['dollarErr', 'pctErr', 'logErr', 'zErr', 'dirHit', 'magRatio', 'skillVsRW'].forEach(k => ok('score.' + k, close(sc[k], exp.score_H1[k]), [sc[k], exp.score_H1[k]]));

console.log('\n' + (fails ? fails + ' FAILED' : 'ALL FIB PARITY TESTS PASSED'));
process.exit(fails ? 1 : 0);
